openedx/frontend-app-gradebook

- .gitignore
- .releaserc
- .travis.yml
- Makefile
- README.md
- docker-compose.yml
- package-lock.json
- package.json
This change updates the values in the repo to:
1. Update documentation that this is gradebook
2. setup for npm publishing.
> WIP Update the Gradebook Repo to setup semantic-release for npm publishing

- README.md
Test out the semantic release functionality
> feat(package): Use this commit to trigger a minor release

- package-lock.json
- package.json
This will allow us to make POSTs in prod.
> fix(auth): use frontend-auth 1.2.0 (allows us to POST without CSRF violation)

- src/components/Gradebook/index.jsx
@iloveagent57 @reillz10 Please review this very simple PR
> fix(ui): update the default wording of the group filters

- src/components/Gradebook/gradebook.scss
- src/components/Gradebook/index.jsx
Add the subtitle to show the course_id
Add the back to dashboard URL to the top right of the page. 
@iloveagent57 @reillz10 Please review.
> fix(functionality): Add links and subtitles to the UI 

- src/data/actions/grades.js
@reillz10 and @iloveagent57 Please review this bug fix.
This is to fix the bug we have on search
> fix(functionality): Fix search so results are rendered with proper heading

- README.md
Adds a note to the README about how to install this into the LMS.  See: https://github.com/edx/edx-platform/pull/19316/files
> Remove boilerplate README strings, add note about installing into LMS.

- src/components/Gradebook/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/actions/grades.js
- src/data/reducers/grades.js
https://openedx.atlassian.net/browse/EDUCATOR-3727
> feat(pagination) added next and previous buttons to grades page

- src/components/Gradebook/gradebook.scss
- src/components/Gradebook/index.jsx
@reillz10 @iloveagent57 @jansenk Please review.
Make it a bit more mobile friendly
> fix(Styles): Fix the gradebook styles to increase its width

- src/components/Gradebook/index.jsx
See screenshot
@iloveagent57 @jansenk @reillz10 Please review.
> fix(UI): Update the percent number view so it is actually percent

- src/components/Gradebook/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/actions/grades.js
after editing a grade, rather than doing a blank lookup we should use the current filter
https://openedx.atlassian.net/browse/EDUCATOR-3769
> fix(filter) filter should remain active after we edit a grade

- src/data/services/LmsApiService.js
Add the page size on the front end so the gradebook only show 10 learners at a time.
@iloveagent57 @reillz10 and @jansenk Please review.
> Add hardcoded page size on frontend

- public/index.html
Hopefully this should cause the &times; character to render correctly
source: https://stackoverflow.com/a/32654216
> fix(UI) specify utf8 to avoid incorrect character rendering

- Makefile
- package-lock.json
- package.json
- src/data/actions/cohorts.test.js
- src/setupTest.js
Setup the unit testing framework in Gradebook.
Will add more examples. But I think this is good to be reviewed by everyone.
@iloveagent57 @reillz10 @iloveagent57
> feat(test): Setup unit testing

- src/data/actions/assignmentTypes.js
- src/data/actions/assignmentTypes.test.js
- src/data/actions/cohorts.js
- src/data/actions/cohorts.test.js
- src/data/actions/grades.test.js
- src/data/actions/tracks.js
- src/data/actions/tracks.test.js
- src/data/reducers/cohorts.js
- src/data/reducers/cohorts.test.js
@reillz10, @iloveagent57 and @jansenk Please review these new batch of tests.
> Add more unit tests on actions and reducers

- config/webpack.dev.config.js
@edx/educator-neem Please review. This makes our local auth on gradebook work just like how it should on production
> fix(auth): fix locally running gradebook auth refresh issue

- src/data/reducers/assignmentTypes.js
- src/data/reducers/assignmentTypes.test.js
- src/data/reducers/cohorts.test.js
- src/data/reducers/grades.js
- src/data/reducers/grades.test.js
- src/data/reducers/tracks.js
- src/data/reducers/tracks.test.js
@edx/educator-neem  Here are all the tests to reducers.
From this point on, I expect unit tests for all functional changes.
> Add all the tests to reducers

- src/components/Gradebook/index.jsx
This is part of the UX review feedback change
@edx/educator-neem Please review.
> Update the color of the alert from red to yellow

- src/components/Gradebook/footer.jsx
> ARCH-321: Dynamic copyright in footer. 

- src/components/Gradebook/index.jsx
@edx/educator-neem Turns out, this is really easy. Please review.
> fix(functionality): Make sure we default select radio button

- src/components/Gradebook/index.jsx
[EDUCATOR-3826](https://openedx.atlassian.net/browse/EDUCATOR-3826)
> Gradebook edit modal updates

- src/components/Gradebook/index.jsx
- src/components/PageButtons/PageButtons.test.jsx
- src/components/PageButtons/__snapshots__/PageButtons.test.jsx.snap
- src/components/PageButtons/index.jsx
refactor buttons to a pure function component
change labels
disable rather than hide
EDUCATOR-3825
> implement gradebook pagination button feedback

- .eslintignore
- config/webpack.common.config.js
- config/webpack.dev.config.js
- package-lock.json
- package.json
- src/data/actions/roles.js
- src/data/actions/roles.test.js
- src/data/store.js
- src/segment.js
@edx/educator-neem Please review.
This PR mimic what's done in https://github.com/edx/edx-portal/pull/29.
It's not meant to be a complete capture of all the events on gradebook. This is an integration to setup tracking on gradebook
All the events should stream into segment.io after deployment.
> Add segment library integration with Gradebook to track events

- src/components/PageButtons/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/actions/grades.js
- src/data/actions/grades.test.js
- src/data/reducers/grades.js
- src/data/reducers/grades.test.js
- src/data/store.js
@edx/educator-neem This PR would add the proper analytics labelling to our tracked events so they are categorized properly.
> fix(analytics): Add the proper labels to analytics for gradebook

- README.md
- src/data/actions/tracks.test.js
- src/data/services/LmsApiService.js
See comments here for explanation: https://openedx.atlassian.net/browse/EDUCATOR-3946
> Include expired course modes when fetching data from course enrollment API

- src/components/Gradebook/index.jsx
- src/components/PageButtons/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/actions/grades.js
- src/data/actions/grades.test.js
- src/data/actions/roles.js
- src/data/actions/utils.js
- src/data/reducers/grades.js
- src/data/store.js
> persist assignment type filter

- src/data/actions/grades.test.js
- src/data/services/LmsApiService.js
> EDUCATOR-3936 Increase users per page from 10 to 25

- package-lock.json
- package.json
- src/data/actions/assignmentTypes.test.js
- src/data/actions/cohorts.test.js
- src/data/actions/grades.test.js
- src/data/actions/roles.test.js
- src/data/actions/tracks.test.js
- src/index.jsx
The 4.0.0 version of frontend-auth resolves an issue where users would be prompted to login more frequently than necessary when reloading the app.
> Upgrade frontend-auth to 4.0.0

- LICENSE
Open edX is supposed to use AGPL (@davidjoy )
> Switch to AGPL

- src/components/Gradebook/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/actions/grades.js
- src/data/reducers/grades.js
> removed username and fake max score

- src/components/Gradebook/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/services/LmsApiService.js
Also some other finalizing details around the gradebook designs from Christine
Depends on https://github.com/edx/edx-bulk-grades/pull/21
JIRA:EDUCATOR-4537
> add intervention filters

- openedx.yaml
> Update openedx.yaml for Masters squad reorg

- README.md
- package-lock.json
- package.json
Related PRs:
- https://github.com/edx/devstack/pull/440
- https://github.com/edx/edx-gomatic/pull/576
- https://github.com/edx/terraform/pull/1852
> Rename gradebook to frontend-app-gradebook

- src/components/Gradebook/gradebook.scss
- src/components/Gradebook/index.jsx
JIRA: https://openedx.atlassian.net/browse/EDUCATOR-4637
and the discussion of the second update made for Olga: https://edx-internal.slack.com/archives/CN0GT0188/p1568140701019300
for the latter, before:
after:
> some more ui updates

- src/components/Gradebook/index.jsx
JIRA:EDUCATOR-4686
@edx/masters-devs
> Set better expectations around file upload processing time

- src/components/Gradebook/index.jsx
- src/data/store.js
Using label property to display courseId in google analytics.
> EDUCATOR-4685 final fix for using label with course id

- src/components/Gradebook/index.jsx
- src/containers/GradebookPage/index.jsx
- src/data/actions/filters.js
- src/data/actions/grades.js
- src/data/store.js
EDUCATOR-4715 - make analytics use redux hooks
> EDUCATOR-4715 working on moving analytics events to redux

- src/index.jsx
> fix: remove youtube logo from footer

- .travis.yml
This would upgrade the node build environment of this repo from 8 to 12
@edx/masters-devs Please review as well.
> Upgrade node build version from 8 to 12

- package-lock.json
- package.json
- src/index.jsx
Update frontend-build that adds the capability to change the webpack.publicPath from environment variables
> fix: Update frontend-build and frontend-platform

- package-lock.json
- package.json
- src/index.jsx
Reverts edx/frontend-app-gradebook#145
> Revert "fix: Update frontend-build and frontend-platform"

- package-lock.json
- package.json
[EDUCATOR-5470](https://openedx.atlassian.net/browse/EDUCATOR-5470)
> EDUCATOR-5470: upgrade semantic-release to 17.2.3

- package-lock.json
- package.json
- src/index.jsx
Changes needed to add again support for subdirectories as a response of https://github.com/edx/frontend-app-gradebook/pull/149
> Follow up to #149

- src/index.jsx
This PR adds the change from https://github.com/edx/frontend-app-gradebook/pull/152.
It is needed in the cases where the environment variable PUBLIC_PATH is not defined.
> Bring change from main branch to koa release

- src/components/Gradebook/BulkManagement.jsx
- src/components/Gradebook/index.jsx
pull Tab wrapper out of BulkManagement component to make react less unhappy with prop-passing
> Bulk mgmt tab fix

- package-lock.json
- package.json
update axios and frontend-platform which depends on it to resolve a security issue.
> update axios and frontend-platform

- src/components/Gradebook/Assignments.jsx
- src/components/Gradebook/index.jsx
- src/data/actions/filters.js
**TL;DR -**
Filters were not updating query params
JIRA: [JIRA-5696](https://openedx.atlassian.net/browse/JIRA-5696)
Filters all update query params
update filters, verify they update the URI.
refresh and make sure they all stick.
> Fix filters2

- package.json
- src/components/Gradebook/BulkManagement.jsx
- src/components/Gradebook/BulkManagementControls.jsx
- src/components/Gradebook/GradebookHeader.jsx
- src/components/Gradebook/GradebookHeader.test.jsx
- src/components/Gradebook/__snapshots__/GradebookHeader.test.jsx.snap
- src/components/Gradebook/index.jsx
- src/containers/GradebookPage/index.jsx
**TL;DR -** 
Pull GradebookHeader component out of monolith and clean up some props.
JIRA: [JIRA-5662](https://openedx.atlassian.net/browse/JIRA-5662)
Basic smoke test should suffice.
> pull GradebookHeader out of monolith

- src/components/Gradebook/index.jsx
- src/components/PageButtons/PageButtons.test.jsx
- src/components/PageButtons/__snapshots__/PageButtons.test.jsx.snap
- src/components/PageButtons/index.jsx
- src/data/selectors/grades.js
- src/data/selectors/grades.test.js
**TL;DR -** 
Fixes PageButtons props.  Some hidden props were passed from Gradebook component to PageButtons, which were removed during de-monolith-ization.  Adding them back in directly to the PageButtons component.
JIRA: [JIRA-5822](https://openedx.atlassian.net/browse/JIRA-5822)
- [ More in depth breakdown of changes ]
- [ Peripheral things that got changed ]
- [ etc... ]
> Fix page buttons

- package-lock.json
- package.json
- src/index.jsx
**TL;DR -** The Gradebook currently passes a lot of unused info to the footer. Mercilessly purge them from the codebase.
JIRA: [EDUCATOR-5773](https://openedx.atlassian.net/browse/EDUCATOR-5773)
Verify that footer behavior/styling is unchanged:
> Trim unused footer props/vars

- package.json
- src/components/GradesTab/EditModal/HistoryHeader.jsx
- src/components/GradesTab/EditModal/HistoryHeader.test.jsx
- src/components/GradesTab/EditModal/ModalHeaders.jsx
- src/components/GradesTab/EditModal/ModalHeaders.test.jsx
- src/components/GradesTab/EditModal/OverrideTable/AdjustedGradeInput.jsx
- src/components/GradesTab/EditModal/OverrideTable/AdjustedGradeInput.test.jsx
- src/components/GradesTab/EditModal/OverrideTable/ReasonInput.jsx
- src/components/GradesTab/EditModal/OverrideTable/ReasonInput.test.jsx
- src/components/GradesTab/EditModal/OverrideTable/__snapshots__/AdjustedGradeInput.test.jsx.snap
- src/components/GradesTab/EditModal/OverrideTable/__snapshots__/ReasonInput.test.jsx.snap
- src/components/GradesTab/EditModal/OverrideTable/__snapshots__/test.jsx.snap
- src/components/GradesTab/EditModal/OverrideTable/index.jsx
- src/components/GradesTab/EditModal/OverrideTable/test.jsx
- src/components/GradesTab/EditModal/__snapshots__/HistoryHeader.test.jsx.snap
- src/components/GradesTab/EditModal/__snapshots__/ModalHeaders.test.jsx.snap
- src/components/GradesTab/EditModal/__snapshots__/test.jsx.snap
- src/components/GradesTab/EditModal/index.jsx
- src/components/GradesTab/EditModal/test.jsx
- src/data/selectors/app.js
- src/data/thunkActions/app.js
**TL;DR -**
Adds docstrings and tests for EditModal and child components.
JIRA: [AU-3](https://openedx.atlassian.net/browse/AU-3)
(Partial completion of ticket)
> refactor: add edit modal tests

- package.json
- src/components/GradesTab/GradebookTable/Fields.jsx
- src/components/GradesTab/GradebookTable/Fields.test.jsx
- src/components/GradesTab/GradebookTable/GradeButton.jsx
- src/components/GradesTab/GradebookTable/GradeButton.test.jsx
- src/components/GradesTab/GradebookTable/LabelReplacements.jsx
- src/components/GradesTab/GradebookTable/LabelReplacements.test.jsx
- src/components/GradesTab/GradebookTable/__snapshots__/Fields.test.jsx.snap
- src/components/GradesTab/GradebookTable/__snapshots__/GradeButton.test.jsx.snap
- src/components/GradesTab/GradebookTable/__snapshots__/LabelReplacements.test.jsx.snap
- src/components/GradesTab/GradebookTable/__snapshots__/test.jsx.snap
- src/components/GradesTab/GradebookTable/index.jsx
- src/components/GradesTab/GradebookTable/test.jsx
- src/data/constants/grades.js
- src/data/selectors/grades.js
- src/data/selectors/grades.test.js
**TL;DR -** 
Cleans up GradebookTable component and adds docstrings and unit tests.
Partial ticket completion
JIRA: [AU-3](https://openedx.atlassian.net/browse/AU-3)
- [ More in depth breakdown of changes ]
- [ Peripheral things that got changed ]
- [ etc... ]
> refactor: gradebook table tests

- package.json
- src/components/GradesTab/BulkManagementControls.jsx
- src/components/GradesTab/BulkManagementControls.test.jsx
- src/components/GradesTab/ScoreViewInput.jsx
- src/components/GradesTab/ScoreViewInput.test.jsx
- src/components/GradesTab/SpinnerIcon.jsx
- src/components/GradesTab/SpinnerIcon.test.jsx
- src/components/GradesTab/UsersLabel.jsx
- src/components/GradesTab/UsersLabel.test.jsx
- src/components/GradesTab/__snapshots__/ScoreViewInput.test.jsx.snap
- src/components/GradesTab/__snapshots__/SpinnerIcon.test.jsx.snap
- src/components/GradesTab/__snapshots__/UsersLabel.test.jsx.snap
- src/components/Header/__snapshots__/test.jsx.snap
- src/components/Header/index.jsx
- src/components/Header/test.jsx
- src/containers/GradebookPage/__snapshots__/test.jsx.snap
- src/containers/GradebookPage/index.jsx
- src/containers/GradebookPage/test.jsx
**TL;DR -** 
Adds in unit tests and docstrings for the remaining components.  Very minor updates to individual components for testing.
JIRA: [AU-3](https://openedx.atlassian.net/browse/AU-3)
Smoke test
> Refactor: add unit tests and docstrings to remaining components

- package-lock.json
- package.json
- src/data/selectors/grades.js
- src/data/selectors/grades.test.js
Ticket[au-66]
**TL;DR -** update csv error according discussed
**JIRA:** [AU-66](https://openedx.atlassian.net/browse/AU-66)
Link  [PR](https://github.com/edx/edx-bulk-grades/pull/87)
> fix: update csv import error messages

- package.json
- src/data/services/lms/urls.js
**TL;DR -** 
Add a missing slash to cohorts fetch URL.
JIRA: [AU-79](https://openedx.atlassian.net/browse/AU-79)
> Fix cohort url

- src/data/services/lms/urls.js
This is a backport of https://github.com/edx/frontend-app-gradebook/pull/213
> fix: build the course_id properly when MFE is deployed in a subdirectory

- src/components/WithSidebar/__snapshots__/test.jsx.snap
- src/components/WithSidebar/index.jsx
**Description:**
Backport PR https://github.com/openedx/frontend-app-gradebook/pull/226 to `open-release/maple.master`.
- Added the ability to manage styles through the main container like in "frontend-app-account" or "frontend-app-profile"
> feat: gradebook main container classname

- package-lock.json
- package.json
This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.
**TL;DR -** [ A short summary of what this PR does and why ]
JIRA: [JIRA-XXXX](https://openedx.atlassian.net/browse/JIRA-XXXX)
- [ More in depth breakdown of changes ]
- [ Peripheral things that got changed ]
- [ etc... ]
> chore: bump frontend-platform (#356)

- package-lock.json
> sync `master` -> `master-design-tokens`
