config/webpack.prod.config.js

Our `LMS_BASE_URL` and other env values are undefined in prod, leading to requests for resources like `https://gradebook.edx.org/undefined/api/grades/v1/gradebook/course-v1:edX+DemoX+Demo_Course/`.  This PR adds keys and default values to the prod webpack config, which should force definition in the environment at build time.

fix(packaging): Add default environment key/value pairs to prod webpack config

---

README.md

Just some notes about things you need to do in the edx-platform Django admin in order to use the gradebook.

Add documentation on platform configuration for local development.

---

src/components/Gradebook/index.jsx

https://openedx.atlassian.net/browse/EDUCATOR-3643
Here's what the whole table looks like (note the "0"s for unattempted subsections):
And here's the edit modal for an unattempted subsection:

Distinguish unattempted subsections.

---

src/components/Gradebook/index.jsx

The second part of the message was never actually true but was left in mistakenly.
Also, I wanted to hide the message while we're loading grades, only show if we for sure can't view gradebook

changed role error message and don't show during loading

---

openedx.yaml

Followup to [EDUCATOR-3853](https://openedx.atlassian.net/browse/EDUCATOR-3853)
@nedbat mentioned we need this file for openedx since gradebook is a main project installed within devstack.

add metadata for openedx releases

---

package-lock.json
src/components/Gradebook/index.jsx

https://openedx.atlassian.net/browse/EDUCATOR-3925
This is to fix the problem in stage
If you go to https://gradebook.stage.edx.org/course-v1:MITx+6.002x+MITx_2012_Alumni and switch to the "Absolute view", you will see broken gradebook. This fixes that partially. We also want an update on the edx-platform API

fix(bug): make sure gradebook rounding handle null input

---

openedx.yaml

Per recent change to OEP-2 https://github.com/edx/open-edx-proposals/pull/112/files
Also, remove track-pulls, which OEP-2 now says is an obsolete property.

Change repo owner from edx/educator-neem to schenedx

---

package.json
src/index.jsx

Note: This is a fix-forward PR.
The `@edx/frontend-component-footer` package now requires the app to be wrapped in the `IntlProvider` component from `react-intl`.
Including the `IntlProvider` component should resolve these errors.

fix forward for including intlprovider

---

src/App.scss
src/components/Drawer/Drawer.scss
src/components/Drawer/index.jsx
src/components/Gradebook/gradebook.scss
src/components/Gradebook/index.jsx

JIRA: https://openedx.atlassian.net/browse/EDUCATOR-4579
Makes gradebook full-width, moving filters into a drawer which pushes the whole page to the side. The portion of the page still visible to the right of the drawer is left-right scrollable & interactible, enabling us to leverage the previously live-updated filters.
There's a good amount more work that would need to go into pulling this new Drawer component out into paragon:
1. There's some keyboard functionality missing (e.g. ESC-key closing & focus save/restore)
2. Configurability around some hard-coded widths (namely the width of the content that doesn't go in the drawer)

Push-aside drawer for filters

---

src/components/Gradebook/index.jsx

@edx/masters-devs 
[EDUCATOR-4629](https://openedx.atlassian.net/browse/EDUCATOR-4629)
On the bulk grades page, removed the "showing X out of Y learners" block copied from the other tab

remove incorrectly copied block

---

src/components/Gradebook/gradebook.scss
src/components/Gradebook/index.jsx

JIRA: https://openedx.atlassian.net/browse/EDUCATOR-4622
along with an issue I haven't stuck in our bug spreadsheet (described below)
before
after

Gradebook styling issues

---

package-lock.json
package.json
src/App.scss
src/components/Gradebook/index.jsx

A minimally-invasive upgrade of paragon from version 4 to 7. I'm happy to say none of the tests broke, and only 1 small UI tweak for spacing's sake.

Upgrade gradebook from paragon 4 to 7

---

src/components/Gradebook/index.jsx

Bug/typo was causing table cells to render at an arbitrary rather than fixed width.
Before: 
After:
JIRA: https://openedx.atlassian.net/browse/EDUCATOR-4973

fix gradebook table cell spacing

---

package-lock.json
package.json
src/components/Gradebook/index.jsx
src/containers/GradebookPage/index.jsx
src/data/actions/grades.js
src/data/actions/grades.test.js
src/data/constants/errors.js
src/data/reducers/grades.js
src/data/reducers/grades.test.js
src/index.jsx

When fetching grade override history, check for new response values `success` and `error_message`, and if `success` is false, display `error_message` rather than the default error message.
I'm not sure what's up with the spacing on the error message. It looks like the existing error message also looks kinda weird when it doesn't completely span the screen. I'll attach some more screenshots.
@edx/masters-devs-gta 
this currently will only work on this branch!! (https://github.com/edx/edx-platform/pull/24849) At least, until the PR is merged

display grade override history error from lms

---

src/components/Gradebook/gradebook.scss
src/components/Gradebook/index.jsx

Css update for table component to allow locked header bar.  Is not a 100% solution, as there are some eccentricities to tables that are a bit wonky for our 100% desired solution.
Note: this is just the css from PR 144, which had some somewhat unrelated JS changes associated.
JIRA: [JIRA-5347](https://openedx.atlassian.net/browse/EDUCATOR-53470)
FIY: @edx/masters-devs-gta

lock header row and column

---

.env
.gitignore
package-lock.json
src/components/Gradebook/Assignments.jsx
src/components/Gradebook/BulkManagement.jsx
src/components/Gradebook/BulkManagementControls.jsx
src/components/Gradebook/EditModal.jsx
src/components/Gradebook/GradebookTable.jsx
src/components/Gradebook/index.jsx
src/containers/GradebookPage/index.jsx

This PR does 2 things.
Css update for table component to allow locked header bar.  Is not a 100% solution, as there are some eccentricities to tables that are a bit wonky for our 100% desired solution.
**NOTE**: PR includes a hack to add a bunch of users into the gradebook table for visibillity of the CSS change.  This is expected to be removed before merge
This PR pulls a number of sub-components out of the Gradebook mega-component.  The final location and implementation of this pull is not solid yet, as this is a phase one of a more concerted future effort, but this split-out should allow these sub-components to be appropriately tested and managed.
JIRA: [JIRA-5347](https://openedx.atlassian.net/browse/EDUCATOR-53470)
FIY: @edx/masters-devs-gta

Locked header and component split-out

---

src/components/Gradebook/gradebook.scss

Use width, instead of min-width for columns to ensure same-size-iness
FIY: @edx/masters-devs-gta

fix column header width to static value

---

package-lock.json
package.json
src/components/Gradebook/Assignments.jsx
src/components/Gradebook/gradebook.scss

**TL;DR -**  Remove `<p>`s acting as duplicate label elements in the "Assignments" filter view in gradebook.
JIRA: [EDUCATOR-5502](https://openedx.atlassian.net/browse/EDUCATOR-5502)
- Removed the following duplicate labels:
- "Assignment Types:"
- "Assignment"
- "Grade Range (0% - 100%)"
- Removed some styling to allow filters to match across filter types
- Run gradebook, verify labels appear as in screenshots and filtering functionality remains
**Before**
**After**

Remove duplicate labels from assignments filter

---

package.json
src/components/Gradebook/index.jsx

**TL;DR -** A typo was preventing assignment name from updating correctly
JIRA: [EDUCATOR-5640](https://openedx.atlassian.net/browse/EDUCATOR-5640)
- Running gradebook locally, click on a grade to bring up the edit grade modal.
- The assignment name should be filled in at the top of the modal.
Before:
After:

fix: typo preventing display of assignment name

---

package-lock.json
package.json
src/components/Gradebook/StatusAlerts.jsx
src/components/Gradebook/StatusAlerts.test.jsx
src/components/Gradebook/__snapshots__/StatusAlerts.test.jsx.snap
src/components/Gradebook/index.jsx
src/containers/GradebookPage/index.jsx

**TL;DR -** break out status alerts into their own component
JIRA: [EDUCATOR-5664](https://openedx.atlassian.net/browse/EDUCATOR-5664)
Regression testing:
- All of the following should result in an error status alert appearing:
- enter a negative value for min course grade and click apply
- enter a value over 100 for min course grade and click apply
- enter a negative value for max course grade and click apply
- enter a value over 100 for max course grade and click apply
- enter a value over 100 for both max course grade and min course grade and click apply
- enter a negative value for both max course grade and min course grade and click apply
- enter a value over 100 for max course grade and a negative value for min course grade and click …

break out status alerts into their own component

---

package-lock.json
package.json
src/components/Gradebook/GradebookTable.jsx
src/components/Gradebook/gradebook.scss
src/data/constants/grades.js
src/data/selectors/grades.js

**TL;DR -** Total Grade should always be displayed as a percent, as it is a percent.
JIRA: [EDUCATOR-5589](https://openedx.atlassian.net/browse/EDUCATOR-5589)
- Total Grade should always be displayed as a percent, as it is a percent.
- Previously we had it out of 100, but that makes it look like somehow the course always has an exact total of 100 points. Let's keep it as always a percent to avoid confusion.
- Refactored the label for the "course grade" column out to a constant
- Re-labeled the column "Total Course Grade"
Change the setting from "Percentage" to "Absolute and back again. The total course grade column should remain a percent.
Collectively, these should be completed by reviewers of this …

EDUCATOR-5589: Total Grade should always be a percent

---

README.md

a.k.a. Override Learner Subsection Scores in Bulk
**TL;DR -** correct link to bulk grade management in README
- there were two links in the README that went to the same section in the docs. I corrected the 2nd link. 
n/a for a doc change
click the link in README.rst

docs: correct link to bulk grade management

---

package.json
src/data/reducers/grades.js

On success and set uploadSuccess to true every time (ordering matter in using spread)
JIRA: [EDUCATOR-5796](https://openedx.atlassian.net/browse/EDUCATOR-5796)
- remove error message from the state
- reorder the spread use so upload success is always true when the upload csv was successful.
- Unit testing was written in a separate commit [EDUCATOR-5780](https://openedx.atlassian.net/browse/EDUCATOR-5780)
FYI: @muselesscreator

Gradebook's csv upload does not clear exist error state on receive data.

---

package-lock.json
package.json
src/components/Gradebook/BulkManagement.jsx

**TL;DR -** Fix a prop name that was causing error banners not to show for bulk management file uploads.
JIRA: [EDUCATOR-5802](https://openedx.atlassian.net/browse/EDUCATOR-5802)
- Fixed a prop name
1. Go to Gradebook configured for bulk grades management
2. Go to the Bulk Management tab
3. Upload an intentionally malformatted CSV (e.g. [NASA's Exoplanet Archive data](https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PSCompPars), exported as CSV is incompatible with bulk grades both because it has the wrong schema and because it exceeds our upload size limitation)
Existing behavior:
- Error banner does not show
Corrected behavior:
- Error banner shows reason for upload error: e.g. …

fix: bad prop causing bulk mgmt errors to not show

---

src/components/GradesTab/GradesTab.scss

**TL;DR -** 
Grade format button in Gradebook has too-short width, causing the caret icon to overlay the text.
Added a slight right-padding to fix.
Before:
After:
JIRA: [AU-30](https://openedx.atlassian.net/browse/AU-30)
- [ More in depth breakdown of changes ]
- [ Peripheral things that got changed ]
- [ etc... ]

add reasonable width to grade format button

---

package.json
src/data/selectors/index.js
src/data/selectors/index.test.js

**TL;DR -** 
Add track filter back into api calls.  This was removed by mistake and was not caught :-(
JIRA: [AU-76](https://openedx.atlassian.net/browse/AU-76)
Add track into api call args for download button.
Add a track filter and download bulk grades.  Make sure they are reflected in the download (or that the network tab shows the track is reflected in the url of the download query)

fix: add track back into lms api service calls.

---

src/data/constants/filters.js
src/data/selectors/filters.js
src/data/selectors/filters.test.js
src/data/selectors/index.js
src/data/selectors/index.test.js

**TL;DR -** 
reworked some badly-located filter logic that was preventing the excludedCourseRoles key from making it into bulk-grades download.
JIRA: [AU-76](https://openedx.atlassian.net/browse/AU-76)
Load a test with staff members.  download bulk grades both With and Without including course members.  Verify that both have data, and that the staff members are missing from file intended to exclude them.

fix: add excludedCourseRoles to bulk-grades fetch

---

src/components/GradesView/GradebookTable/LabelReplacements.jsx
src/components/GradesView/GradebookTable/LabelReplacements.test.jsx
src/components/GradesView/GradebookTable/__snapshots__/LabelReplacements.test.jsx.snap
src/components/GradesView/GradesView.scss
src/setupTest.js

**Description:**
Backport PR https://github.com/openedx/frontend-app-gradebook/pull/225 to `open-release/maple.master`.
- Fixed gradebook table arrow tooltip position in RTL direction

fix: gradebook table rtl tooltip position

---

package-lock.json
src/components/GradesView/GradebookTable/__snapshots__/test.jsx.snap
src/components/GradesView/GradebookTable/messages.js
src/i18n/messages/ar.json
src/i18n/messages/es_419.json
src/i18n/messages/fr.json
src/i18n/messages/zh_CN.json
src/i18n/transifex_input.json

**TL;DR** - I suggest adding the `*` sign to the email column name to identify that its data is available for masters track only (like for the "student key"). Because the [grades API code says](https://github.com/openedx/edx-platform/commit/68ec2e184d1b4ed7824954e34c97bef39647ebe2#diff-73ff878afa65080c863cd832be2d019b2882bd7c0544a45ecb26778757f7423dR155) that the data for that column only available for the masters mode.

fix: add an asterisk to the 'Email' name of column

---

package-lock.json
src/components/GradesView/SearchControls.jsx
src/components/GradesView/SearchControls.test.jsx
src/components/GradesView/__snapshots__/SearchControls.test.jsx.snap

**TL;DR -** Fixed loss of field focus after each character for the search field.
The cause of the problem is the last requirements upgrade for the paragon package from `14.16.4` to `19.6.0`. In the paragon library, the `SearchField` was significantly changed and currently after every key press it losses the field focus.

fix: fix loss of field focus after each character for search field

---

package-lock.json
src/data/services/lms/api.js
src/data/services/lms/api.test.js
src/data/services/lms/urls.js
src/data/services/lms/urls.test.js

feat: ensure lms api synced with latest value in config

---

src/data/selectors/index.js
src/data/selectors/index.test.js

When the assignment type is selected, but the assignment id isn't - the courseGradeMax, courseGradeMin assignmentGradeMax and assignmentGradeMin values become nullable. This leads to incorrect filtering results.
The issue demo:
Fix:
- Preserve the courseGradeMax and courseGradeMin values in such cases;
The fix demo:

fix: correct grades minmax values

---

src/components/GradesView/EditModal/OverrideTable/AdjustedGradeInput.jsx
src/components/GradesView/EditModal/OverrideTable/AdjustedGradeInput.test.jsx
src/components/GradesView/EditModal/OverrideTable/__snapshots__/AdjustedGradeInput.test.jsx.snap

**TL;DR** - added simple validation for the "Adjusted grade" field in the "Edit Grades" popup:
- enter only a numeric value
- setting the minimum value
- checking the correctness of the entered value to possibleGrade

feat: add a simple validation to the adjusted grade field

---

src/components/GradesView/EditModal/OverrideTable/__snapshots__/test.jsx.snap
src/components/GradesView/EditModal/OverrideTable/index.jsx

**TL;DR -** The problem was in the rows counter in the Edit Grades modal window. First digit - number of lines excluding the last line with the form. Second digit - grades data. And our proposal is to include last row with form to common counting

fix: Fix rows counter in the Edit Grade modal window (olive branch)

---

src/components/GradesView/ImportGradesButton/hooks.js

This is a [backport](https://github.com/openedx/frontend-app-gradebook/pull/323) from the master branch.
hasFile run only once, it will always be null

fix: file input handler

---

src/App.jsx
src/App.test.jsx
src/data/constants/app.js

See https://github.com/openedx/frontend-app-gradebook/pull/375 for a description.

[Quince backport] fix: Route with PUBLIC_PATH

---

src/components/GradebookHeader/__snapshots__/index.test.jsx.snap
src/components/GradebookHeader/index.jsx
src/components/GradesView/FilterMenuToggle/__snapshots__/index.test.jsx.snap
src/components/GradesView/FilterMenuToggle/index.jsx
src/components/GradesView/GradesView.scss
src/components/GradesView/SearchControls/__snapshots__/index.test.jsx.snap
src/components/GradesView/SearchControls/index.jsx
src/components/GradesView/__snapshots__/index.test.jsx.snap
src/components/GradesView/index.jsx

**TL;DR -**
This pull request contains minor fixes related to the responsiveness of the blocks for mobile phones. All the before and after screenshots are below.
**Related Pull Requests**
PR to the open-release/palm.master branch: https://github.com/openedx/frontend-app-gradebook/pull/362
PR to the master branch: https://github.com/openedx/frontend-app-gradebook/pull/363
- fixed text overload in the title when the course ID is too long
|  Before |  After |
|---|---|
|  <img width="427" alt="image" src="https://github.com/openedx/frontend-app-gradebook/assets/17108583/71ccc26b-1098-47fa-92fb-162816071dc8"> |  <img width="374" alt="image" src="https://github.com/openedx/frontend-app-gradebook/assets/17108583/8c5c5803-0d7d-4821-b0c8-afc127c9c1d0"> |
- fixed appearance and …

fix: fix sidebar scrolling and adaptation for mobile

---

src/components/GradesView/EditModal/OverrideTable/hooks.js

**This is a [backport](https://github.com/openedx/frontend-app-gradebook/pull/387) from the master branch.**
Hi! I found a bug.
1. Open Instructor -> Student admin -> View gradebook
2. Click on some grade
3. Set new grade or just click Cancel
4. Open same grade or another one
This happens because `doneViewingAssignment()` executes when the modal window closes. The redux state is being cleaned, namely, `gradeOverrideHistoryResults` is removed. 
Because of this, when we access this element again, we do not get the expected iterable object (list), but we get an `undefined`.
Previously, this was eliminated by the [default value](https://github.com/openedx/frontend-app-gradebook/blob/66bae174dd7f127844678d02b0784d42be0c2c43/src/components/GradesView/EditModal/OverrideTable/index.jsx#L53).
My …

fix: "An unexpected error occurred" after second opening any grade

---

src/components/GradesView/EditModal/OverrideTable/__snapshots__/index.test.jsx.snap
src/components/GradesView/EditModal/OverrideTable/hooks.js
src/components/GradesView/EditModal/OverrideTable/index.jsx

This is backport from master - https://github.com/openedx/frontend-app-gradebook/pull/310
**TL;DR -** The problem was in the rows counter in the Edit Grades modal window. First digit - number of lines excluding the last line with the form. Second digit - grades data. And our proposal is to include last row with form to common counting

fix: Fix rows counter in the Edit Grade modal window
